### ISSUE TITLE
[feature] remove some files from a collection in use for a given data selection 

### ISSUE THREAD

**Issue by gmella** [JMMC-OpenDev/oiexplorer#2]
**Is your feature request related to a problem? Please describe.**
I would like to be able to remove a given file from the current collection.

**Describe the solution you'd like**
Selecting a file from the current set and getting a delete shortcut or button would provide a way to adjust properly the content of my collection.

**Describe alternatives you've considered**
Reset the collection and start adding files without the one we do not want anymore. In this case, we loose every plots attached to the session.

**Additional context**
no

**Reworked specifications** 

First implementation will cover next scenario updating the current version:
- A selection in the data tree panel (bottom left selector) defines the subset of data that must be removed from the collection
- A remove data button will be added to the mainPanel.toolBar
- Clicking on the button will ask for confirmation to the user 
- The shown data reported by the dialog box will be removed from the collection if the user confirm, else operation is aborted
- User already may look on Subset's associated files looking at highlighted entries in the Files tab of the Granules Tree Panel

The report shown in the confirmation dialog must provide in the first version:
- for each file to be removed :
  -  its path
  - for each targets:
    - the number of data tables
This must help the user to detect some side effect, e.g. removing a file from a single table selection of a file that contains multiple granules will remove every granules.

Validation will be done trying to:
- remove a table from a collection that contains a single file
  - operation succeed if the application have the same behavior as running "New Oifits Collection" : collection is empty / no leak 
- remove a target from a collection that contains single granule files for various targets
  -  operation succeed if the collections shows the total number of previous targets - 1

Note: 
- this feature does not cover the data filtering but help the user to remove faulty oifits load

**Comment by buthanoid** [comment]
### existing (potentially) useful code
- `oiexplorer.core.OIFitsCollectionManager.removeOIFitsFile(OIFitsFile)`
  Function that removes the `OIFitsFile` from the `OIFitsCollection` and from the `OIDataCollection`. Then casts a `COLLECTION_CHANGED` event.
- `oiexplorer.OIFitsFileListPanel.updateOIFitsList(OIFitsCollection)`
  Function that contains a code to compute the list of `OIFitsFile` concerned by the current `SubsetDefinition`.
  It just uses the built `OIFitsFile` from the `SubsetDefinition`, then it takes advantage of the fact that the `OIDatas` still reference their "main" `OIFitsFiles` (i.e the ones stored in `OIFitsCollection`).
- `oitools.OIFitsCollection.findOIData(Selector)`
  Function that returns a SelectorResult containing the OIDatas corresponding to the Selector in parameter.
- `jmcs.MessagePane.showDialogPanel(String,JPanel)`
  Function that display a dialog panel

### Feature realization proposition

#### delete an OIFitsFile from the data 

already realized by `OIFitsCollectionManager.removeOIFitsFile`

#### ask to delete ONE precise file from the GUI

Actually I think it is not so obvious where this could fit in the current GUI. There is two places where files appear, they are both in the GranuleTreePanel, one in the GranulesTab and the other in the FilesTab. 

The Files in the GranuleTab can be selected. Until now, no action was associated to this selection. We could add a "Delete File" in the button bar, that would delete the selected file in GranuleTreePanel.Granules. However, because the DataTreePanel also have a concurrent selection, and that DataTreePanel is more the "action" panel compared to GranuleTreePanel, it would not be crystal-clear to the user which selection will be concerned by the button. So I would advocate for a "right-click -> delete file" directly on the item of GranuleTreePanel.Granules. 

About GranuleTreePanel.Files, there is a list of files, and an existing "Browser" button, but the user can make no selection, so I do not think a Delete button would be practical, and I actually think the current browser button is not practical either. I would advocate a button here only if the user can directly select the file, but this does not fit with the original behaviour of that panel which is to display which files are concerned by the current `SubsetDefinition`.

#### Delete all files concerned by the current SubsetDefinition

Obtaining that list of files is easy because it is already done in `OIFitsFileListPanel.updateOIFitsList`. We just have to move that code to `SubsetDefinition`. Then we remove each file, we could add a method in `OIFitsCollectionManager` to delete a list of Files, to avoid casting many events. We could factor the common code with `removeOIFitsFile`.

The GUI button could be in the button bar, it could be called "Delete associated files". 

#### Delete all files concerned by a Target or an Instrument Mode or Table

We could add the feature of a right-click on a Target or Instrument Mode or Table from the DataTreePanel, leading to a righ-click menu with the item "Delete associated file(s)".  That action would *not* change the current selection and the current `SubsetDefinition`. I think it is not a mandatory feature.

In the code part, it would need to build a Selector depending on the clicked item, and to send it to the function `OIFitsCollection.findOIData`. Then we would obtain a list of OIDatas that would lead us to the list of files to delete.\
Alternatively, we could also create a temporary SubsetDefinition that would follow the process of Filters, Selector, SelectoResult, to OIFitsFile, and then using the code from `OIFitsFileListPanel.updateOIFitsList` like in the previous section.

#### dialog confirm with details

In all cases, I advocate for a dialog confirm before actually deleting the file(s).
That dialog would list the files to be deleted, and then the list of OIDatas with the Target and Instrument Mode, similar of the information that we see in the DataTreePanel. 
Because when you right click on a Target on "Delete associated files", you need to see the list of concerned files. And since you cannot delete half of a file, you need to see the list of associated Tables that will be removed.
JMCS already has the function `MessagePane.showDialogPanel` for the dialog subwindow.

### questions
- are we sure that just after `removeOIFitsFile` has removed the `OIFitsFile` and just before the `COLLECTION_CHANGED` event is handled, no other event could be handled that would use or try to use the deleted `OIFitsFile`  ? 

### basic test cases

not exactly elementary to avoid too many cases

#### delete one file

- add one file
- delete this file
- nothing should remain

#### delete one target from two files with two targets

- add one file with one target
- add another file with another target
- delete one file
- only the other file, its targets and its tables should remain

#### delete one instrument mode from two files with the same instrument mode

- add one file with one instrument mode
- add another file with the same instrument mode
- delete the instrument mode
- nothing should remain

#### delete one table from one file with two targets

- add one file with two targets
- delete one table
- nothing should remain

### What remains to be specified

Hopefully I will have completed it before the meeting.

- For the dialog, how to get the information about the associated tables like in the DataTreePanel. help ?

**Comment by bourgesl** [comment]
Analysis:
- `oiexplorer.core.OIFitsCollectionManager.removeOIFitsFile(OIFitsFile)` is present (not tested ?) that will remove the given OIFitsFile from the OIFitsCollection and from the OIDataCollection.
- how to retrieve the correct OIFitsFile(s) from the current subset ? use the subset's OIFitsFile (virtual) that gives the selected OITables whom the real OIFitsFile can be retrieved. See a similar algorithm in the OIFitsFileListPanel.updateOIFitsList(OIFitsCollection)
 
Design proposal:
- add a button in the main toolbar
- add a variant OIFitsCollectionManager.removeOIFitsFile(List<OIFitsFile>) to send a single CollectionChanged event
- add the button action in the OIFitsFileListPanel that reuses the selected OIFitsFile(s) to display the confirm dialog and call OCM.removeOIFitsFile(list) ...
- the confirm dialog will be simpler: 'file (nb targets, nb VIS2, nb T3, nb VIS ...)' using the OIFitsFile API (no granule handling)

**Comment by buthanoid** [comment]
My work in https://github.com/JMMC-OpenDev/oiexplorer-core/pull/11 and https://github.com/JMMC-OpenDev/oiexplorer/pull/4

**Comment by bourgesl** [comment]
PR integrated

**Comment by bourgesl** [comment]
See http://jmmc.fr/~betaswmgr/OIFitsExplorer/
