### ISSUE TITLE
[feature] Handle multiple selection in the bottom left tree 

### ISSUE THREAD

**Issue by gmella** [JMMC-OpenDev/oiexplorer#3]
**Is your feature request related to a problem? Please describe.**
I would like to export a subset of data located under several branches or leafs.

**Describe the solution you'd like**
Support of multiple selection would allow to merge/export data in a much better way. 

**Describe alternatives you've considered**
If I need to merge 2 branches over 3, I can export both of interest, then reset the collection, load last 2 exported and export/merge the whole collection. 

**Additional context**
please consider ctrl / shift click to facilitate selection :)

**Comment by buthanoid** [comment]
My current notes:

- DataTreePanel uses GenericJTree, a JMCS subclass of Swing JTree. It is made for Single Selection and work must be done to adapt it to Multiple Selection. JTree already handles Ctrl and Maj keys for easy selection.
  - Laurent's answer: it should not be difficult to adapt GenericJTree.
- A multiple selection is a union of simple selections, therefore simple each selection will be mapped to a Selector.
- The Merger uses the SelectorResult computed from the current SubsetDefinition. The merger seems to be able to cope with several night ids so it can cope with several SubsetFilter with different night ids. However it also use "the" Selector of the SelectorResult. This confuses me because I understand the SelectorResult to be a union of Selectors (see function `OIFitsCollection.findOIData(Selector,SelectorResult)`). A unique Selector is therefore incomplete in regards to the SubsetDefinition which can have several SubsetFilters.
- compatibility with Remove is complete because the multiple selection is completely represented by the current SubsetDefinition, so the list of selected files is complete.
- TODO: check code that will treat multiple SubsetFilters (as the current gui always have only one) (for example: plotcharpanel must uses all subsetfilters to filter the data)

**Comment by bourgesl** [comment]
Let's start supporting multiple selection of table items (same target, same insmode)

**Comment by buthanoid** [comment]
# Brief

- contiguous selection returns several paths. To have several selected tables, we need several paths. Note that various other paths unwanted by this feature can be selected by the user. I suggest to ignore this fact for now.
- some easy interface functions must be added to `GenericJTree` (get all selected paths, select several paths)
- `DataTreePanel.updateOIFitsCollection` is the function that make a tree from an oifitsCollection. It must use all tables of the argument susbset definition, in order to collect all nodes to correctly select all concerned paths.
- `DataTreePanel.valueChanged` is the function that modify the current subset definition, when the user select something on the tree. It must gets all selected paths from `GenericJTree`. It must collect all tables then call `processSelection` at the end to update the filter of the currentSubsetDefintion.
- the subsetFilter can already handle several tables, it is also true for current code using subsetFilter (excluding functions cited here)

# Detailed

## GenericJTree

The class that wraps a JTree

- in the constructor, set selectionMode to `CONTIGUOUS_TREE_SELECTION`. Note that this enables targetting of various multiple paths (not only the same instrument with several of its tables). I suggest to not adress this issue as the plan seems to be able to cover multiple paths later.
- `getLastSelectedNode` returns the leafest node of the last of the selected paths. This is typically a `SINGLE_TREE_SELECTION` feature. It is called by `DataTreePanel.valueChanged`. Another method should be added to return instead `TreePath[] JTree.getSelectionPaths()` which gives all the selected paths.
- `selectPath` set the selection to the given path. Can be kept it is used for example to select the root node. BTW `addNodeAndRefresh` seems unused code. However I think we need a function to select several paths, see section DataTreePanel below. 
- a remark about the paths selected by a `DIS/CONTIGUOUS_TREE_SELECTION`. Say there is an expanded tree, with `INS_MODE_A` which contains `TABLE_1`, and `INS_MODE_B` which contains `TABLE_2`. Left-Clicking on `TABLE_1`, then  MAJ+Left-Clicking on `TABLE_2` gives three selected paths: `INS_MODE_A->TABLE_1`, `INS_MODE_B`, `INS_MODE_B->TABLE_2`. The second path `INS_MODE_B` selects every table from `INS_MODE_B`. I have a feeling it is going to be weird in the GUI, we will see.

## DataTreePanel

The Panel that display and features the selection. It uses `GenericJTree`.

- remove // TODO: support multiple table selections :P
- `updateOIFitsCollection`: uses only the first of the tables of the filter of the current subset definition. It looks for the selected table and store the associated node, then select its path. Just needs to stores several nodes, and then call `GenericJTree.selectPaths` (with an `s`). TODO comment to remove.
- `valueChanged`: processes tree selection. works with `getlastSelectedNode`. Must be changed to work with multiple paths, as multiple selected tables will be represented as multiple paths. Here I will assume that if there is several paths, then they all point to some table belonging to the same target and same instrument mode (see first bullet of GenericJTree section). `processSelection` must be called at the end, after collecting all tables.
- `processSelection`: another variation must be added to work with several tables instead of one. easy since it can use the first filter as in the current version. 

## SubsetFilter

- every code I saw which were calling `getTables` seemed to behave correctly with several tables.  (excluding functions cited here)

## GranuleTreePanel

- There is a TODO about multiple selection. But I don't currently see a synch between the two panels selections so I don't plan to change something.

**Comment by gmella** [comment]
Starting supporting multiple selection of table items (same target, same insmode), we decide to keep compatible table only from the user selection. After analysis, the software refines a valid selection and sync the tree.

**Comment by bourgesl** [comment]
Change proposal:
- enhance `GenericJTree` to add methods `getSelectedNodes() `and `selectPaths()` to deal with `TreePath[]` values
- change `DataTreePanel.valueChanged()` to handle tree selections and call `processSelection(String targetUID, String insModeUID, List<OITable> oiTables)` to update the single `SubsetDefinition` and its single `SubsetFilter` with the following rules:
   - consider only the first target (same ancestor) to define the target UID: `filter.setTargetUID(targetUID)`; other targets are ignored to be unselected.
   - define the optional insMode UID criteria only if the criteria insModeUID is unique else NULL : `filter.setInsModeUID(insModeUID)`
   - define the selected OITables (multiple values) from the tree selection (same target UID): `filter.getTables().add(new TableUID(...) )`
   - if intermediate tree nodes are selected (target, insmode), please unselect them when table nodes are selected.
